name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true
        default: 'v0.0.1'
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]  # 支持多个操作系统
        go-version: [ '1.23.3' ]  # 你需要的 Go 版本

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            # gcc
            sudo apt-get install -y gcc libc6-dev
            # x11
            sudo apt-get install -y libx11-dev xorg-dev libxtst-dev
            # Clipboard
            sudo apt-get install -y xsel xclip
            # Bitmap
            sudo apt-get install -y libpng++-dev
            # GoHook
            sudo apt-get install -y xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install libpng libjpeg libx11
          fi

      - name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=amd64 go build -o robotgo-server-${{ matrix.os }}-${{ matrix.go-version }} .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: robotgo-server
          path: robotgo-server-${{ matrix.os }}-${{ matrix.go-version }}
