name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true
        default: 'v0.0.1'
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go-version: [ '1.23.3' ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            # gcc
            sudo apt-get install -y gcc libc6-dev
            # x11
            sudo apt-get install -y libx11-dev xorg-dev libxtst-dev
            # Clipboard
            sudo apt-get install -y xsel xclip
            # Bitmap
            sudo apt-get install -y libpng++-dev
            # GoHook
            sudo apt-get install -y xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install libpng libjpeg libx11
          fi

      - name: Build
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o dist/robotgo-server-linux-amd64
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 go build -o dist/robotgo-server-darwin-amd64
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            GOOS=windows GOARCH=amd64 CGO_ENABLED=1 go build -o dist/robotgo-server-windows-amd64
          fi

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          allowUpdates: true
          makeLatest: false
          tag: ${{ steps.get-tag.outputs.tag }}
          artifacts: 'dist/*'
          token: ${{ secrets.GITHUB_TOKEN }}
